In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[72, 15],
       [80, 16],
       [37, 50],
       [62, 45],
       [67, 36],
       [61, 79],
       [10,  2],
       [ 5, 73],
       [66, 85],
       [55,  6]])

## Using Scikit Learn for Preprocessing Data

Lets assume that data is the data we have. If we are going to use this data in our neural network model one of the first things that we are going to do is to scale the data.

In [9]:
scaler_model = MinMaxScaler()

Basically create a `MinMaxScalar` instance

In [12]:
scaler_model.fit(data) # we are fitting the data to the MinMaxScaler model

C:\Users\Rajdeep\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [13]:
scaler_model.transform(data) # transforming the data 

array([[0.89333333, 0.15662651],
       [1.        , 0.1686747 ],
       [0.42666667, 0.57831325],
       [0.76      , 0.51807229],
       [0.82666667, 0.40963855],
       [0.74666667, 0.92771084],
       [0.06666667, 0.        ],
       [0.        , 0.85542169],
       [0.81333333, 1.        ],
       [0.66666667, 0.04819277]])

In [14]:
# Here as we can clearly see that the minimum value has become zero and the maximum value has become 1. 
# There are obviously other scalers found

In [15]:
scaler_model.fit_transform(data)

C:\Users\Rajdeep\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.89333333, 0.15662651],
       [1.        , 0.1686747 ],
       [0.42666667, 0.57831325],
       [0.76      , 0.51807229],
       [0.82666667, 0.40963855],
       [0.74666667, 0.92771084],
       [0.06666667, 0.        ],
       [0.        , 0.85542169],
       [0.81333333, 1.        ],
       [0.66666667, 0.04819277]])

The **ScalerModel** should only be fitted to your training data. The idea is that we need to fit to our training data and then
transform our training data and then transform our test data

In [16]:
import pandas as pd

In [18]:
mydata = np.random.randint(0,101,(50,4))

In [21]:
data = pd.DataFrame(data=mydata, columns=['f1', 'f2', 'f3', 'label'])

Here the first 3 columns are essentially columns of the 3 features and the label is a separate label

In [23]:
data

f1  f2   f3  label
0   68  44   40     37
1   44  11   25     36
2   34  11  100     47
3   29  77   51     92
4   28  47   47     99
5   41  94   35     37
6   94  66   70     10
7   11  60   66     81
8    0  75   65      5
9   68  26   53     91
10  65  51   10     50
11  96  24   69     29
12  86  10   90     33
13  29  97   91     84
14  42  97    7     80
15  24  42   45     37
16  77  24   77     92
17   6  82   48     52
18  89  13   74     86
19  11  89    1     54
20   8   7   55     94
21  32  16   69     96
22  32  93   40     88
23  82  53   44     54
24  88  58   46     53
25  37  89   33      7
26  67  93   85     68
27  61  46   97     20
28   1  58    2     84
29  15  96   95     89
30  82  56   37     36
31  45  66   30      3
32  46  77   47     72
33   5  45   69     35
34  66  40   52     66
35  23   4   64     30
36  96  37   99     80
37  74  33   86     13
38   8   5   89     21
39  76  44   92     52
40  69  52   10     60
41  52  72   83     35
42   3  18   15     69
43  62  32   93     18
44  52  22   98     13
45  44  23   87     40
46  56  77   24     11
47  77   2   59     60
48  28  38   78     31
49  36  55   24     31

In [24]:
# lets split this into a training and test dataset

In [25]:
X = data[['f1', 'f2', 'f3']]

In [26]:
y = data['label']

In [27]:
# now we have the features and the labels

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
# test_size is simply the percentage of the data that we want to go to the test set
# random_state is simply like the seed in a random number generator, the idea is to always shuffle before getting into the train
# and test sets

In [32]:
type(X_train)

pandas.core.frame.DataFrame

In [33]:
X_train.shape

(33, 3)

In [34]:
X_test.shape

(17, 3)